apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  real-ip-header: "X-Forwarded-For"
  set-real-ip-from: "0.0.0.0/0"
