apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: orders
  POSTGRES_PASSWORD: "Shamrock23$"
  POSTGRES_DB: ordersdb
  DB_HOST: postgres
  DB_NAME: ordersdb
